version: '3'

services: 
    frontend:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        tty: true
        ports: 
            - "4000:3000"
        restart: on-failure